[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]
cmds = ["useradd -m -s /bin/bash node || true"]

[phases.install]
cmds = ["npm install", "npm install -g serve"]

[phases.build]
cmds = ["npm run build", "chown -R node:node /app || true"]

[phases.start]
cmds = ["su -p node -c \"PATH=$PATH serve -s dist -l 3000\""]
